symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 300 # durée de validité du lien (1h ici)
    throttle_limit: 3600 # délai entre deux demandes
